# Meta store config
meta_store:
  # Available types: sqlite
  meta_db_type: sqlite

  # Path to the meta database
  meta_db_path: meta.db

# Private store config
private_store:
  # Available types: sqlite
  private_db_type: sqlite

  # Path to the private database
  private_db_path: private.db

# Vector store config
vector_store:
  # Available types: sqlite
  vector_db_type: sqlite

  # Path to the vector database
  vector_db_path: vector.db

# Reranker config
reranker:
  # Available types: bm25
  reranker_type: bm25
  k1: 1.2
  b: 0.75

# Summarizer config
summarizer:
  # Available types: textrank
  summarizer_type: textrank
  top_k: 5
  min_score: 0.1

# Vectorizer config
vectorizer:
  # Available types: sentence_transformer
  vectorizer_type: sentence_transformer
  model_name: all-MiniLM-L6-v2
  device: cpu

# Chunker config
chunker:
  # Available types: chonkie_recursive
  chunker_type: chonkie_recursive
  chunk_size: 1000
  chunk_overlap: 100